ktor:
  deployment:
    port: 8080
    host: 0.0.0.0
  application:
    modules:
      - com.example.DatabaseKt.configureDatabase
      - com.example.StatusPagesKt.configureStatusPages
      - com.example.plugins.AuthKt.configureAuth
      - com.example.RoutingKt.configureRouting
      - com.example.SerializationKt.configureSerialization
      - com.example.SecurityKt.configureSecurity
      - com.example.WebsocketsKt.configureWebsockets
      - com.example.RpcKt.configureRpc
      - com.example.ResourcesKt.configureResources